# Course 1. Mathematical Epidemiology {#course1 .unnumbered}

This course will cover different formulations and analyses of epidemiological models. Topics include host heterogeneity, multiple pathogens, spatial spread, within-host dynamics, and zoonotic spillover.

Some lectures will be based on [Modelling Infectious Diseases in Humans and Animals](http://www.modelinginfectiousdiseases.org/) by Matt Keeling and Pejman Rohani. This book is usually available for download as an ebook from university libraries.


[Course outline (downloadable .pdf)](https://github.com/ahurford/aarms-summer-school/blob/main/syllabi/MATH%206115%20Mathematical%20Epidemiology%20Final.pdf)

AARMS Summer School format:

- 15 lectures [schedule: [week 1](#week1); [week 2](#week2)]
- 2 guest lectures [schedule: [week 1](#week1); [week 2](#week2)]
- 8 problem sets [link](#mathepiprobs)
- A final project [link](#projects)

For participants with limited prior math courses, see [here](#prep) for suggested preparation.

For participants with limited prior stats courses, see [here](#prepstats) for suggested preparation.

For participants with limited coding experience, see [here](#prepcoding) for suggested preparation.

- **Lecture 1. Simple models.** [slides](https://github.com/ahurford/ss-amy-greer/blob/main/August%2020_2023/Simple%20Models/Lecture%201_Simple%20Epi%20Models_Greer_handouts.pdf)

- **Lecture 2. Host heterogeneity.** [slides](https://github.com/ahurford/ss-amy-greer/blob/main/August%2020_2023/Heterogeneity%20Part%201/Greer_Heterogeneity_Part1_handouts.pdf)

- **Lecture 3. Host heterogeneity.** [.pdf](August 21_2023/Heterogeneity Part 2/Greer_Heterogenity-Exercise_Part2.pdf) [.Rmd](https://github.com/ahurford/ss-amy-greer/blob/main/August%2021_2023/Heterogeneity%20Part%202/Heterogenity%20Exercise_Part2.Rmd) [.RData](https://github.com/ahurford/ss-amy-greer/blob/main/August%2021_2023/Heterogeneity%20Part%202/data.RData)

- **Lecture Heffernan-1. Multi-host Multi-pathogen** [.html](slides-multihost-multipath.pdf)

- **Lecture Heffernan-2. Evolution** [.html](slides-evolution.pdf)

- **Lecture Heffernan-3. Seasonality** [.html](slides-seasonality.pdf)

- **Lecture ??. Stochastic models.** [.html](2023-08-24-AARMS-stochastic.html)


- **Lecture 13. Zoonotic spillover.** [reading](https://royalsocietypublishing.org/doi/10.1098/rstb.2018.0435) [slides](https://github.com/ahurford/ss-amy-greer/blob/main/August%2027_2023/Zoonotic%20spillover/Greer_Spillover_Part1_handout.pdf)

- **Lecture 14. Zoonotic spillover II.** [slides](https://github.com/ahurford/ss-amy-greer/blob/main/August%2027_2023/Zoonotic%20spillover/Greer_Spillover_Part2_handout.pdf)

- **Lecture 15. Controlling infectious disease.**  [slides](https://github.com/ahurford/ss-amy-greer/blob/main/August%2029_2023/Controlling%20Infectious%20Diseases/GREER_Controlling%20ID_handouts.pdf)

