## Schedule

- Saturday August 19: arrive (if staying at BBMS check-in is ???)

- Sunday August 20: Math Epi (Lecture 1-2 + Problems 1, 3hrs); Data (same); 1 hr projects

- Monday August 21: Math Epi (Lecture 3-4 + Problems 2, 3hrs); Data (same); Guest lecture 1

- Tues August 22: Math Epi (Lecture 5-6 + Problems 3, 3hrs); Data (same); 1 hr projects

- Wed August 23: Math Epi (Lecture 7-8 + Problems 4, 3hrs); Data (same); Guest lecture 2

- Thurs August 24: Math Epi (Lecture 9-10 + Problems 5, 3hrs); Data (same); 1 hr project

- Fri August 25: Math Epi (Lecture 11-12 + Problems 6, 3hrs); Data (same); Guest lecture 3

- Sat August 26: Math Epi (Lecture 13-14 + Problems 7, 3hrs); Data (same); 1 hr project

- Sun August 27: Math Epi (Lecture 15 + Problems 8, 2hrs); Data (same); 3 hrs projects

- Mon August 28: Math Epi (Lecture 15 + Problems 9, 2hrs); Data (same); 3 hrs projects

- Tues August 29: Math Epi (Lecture 16 + Problems 10, 2hrs); 5 hrs projects

- Wed August 30: Data (Lecture 16 + Problems 10, 2hrs); 5 hrs projects
