# Course 2. Data, models, and decision support {#course2 .unnumbered}

During the COVID-19 pandemic mathematical modelling provided decision support through forecast modelling, exploration of counter-factual scenarios, and guided public communication. This course will teach the technical skills to estimate model parameters, fit models to data, and describe the uncertainty of model predictions. We will explore the use of models in public health communications during the COVID-19 pandemic to understand how models provide decision support. Some lectures will be from [Ecological forecasting](https://press.princeton.edu/books/hardcover/9780691160573/ecological-forecasting).

Format:

- 15 lectures (Course 2)
- 3 guest lectures (both courses)

Grading:

- 8 x problem sets (Course 2)
- 1 x pre-requisite problem set (both courses)
- 1 x project (both courses)

Students will work in groups of 2-3 to complete a project. Project descriptions will be provided by the instructors. Specific expertise of the instructors includes spatial epidemiology, importations, within-host models, zoonotic spillover, and COVID-19. 