# Course 1. Mathematical Epidemiology {-}

This course will cover different formulations and analyses for mathematical models in epidemiology. Some lectures will be based on [Modelling Infectious Diseases in Humans and Animals](http://www.modelinginfectiousdiseases.org/) by Matt Keeling and Pejman Rohani (available as .pdf from MUN library). More details on specific topics can be found below.

- Lecture 1. Ch 2. Simple Epidemiological Models

- Lecture 2. Ch 3. Host Heterogeneity I

**Problems 1.**

- Lecture 3. Ch 3. Host Heterogeneity II 

- Lecture 4. Ch 4. Multipathogen/Multihost 

**Problems 2.**

- Lecture 5. Evolutionary epidemiology (Hurford)

- Lecture 6. Ch 5. Temporally-forced models 

**Problems 3.** 

- Lectures 7. & 8. Within-host dynamics (Heffernan)

**Problems 4.**

- Lecture 9. Ch 6. Stochastic dynamics (models only, i.e. excluding 6.1 and 6.2) 

- Lecture 10. Ch 7. Spatial models I

**Problems 5.**

- Lectures 11. Ch 7. Spatial models II 

- Lecture 12. Modelling importations (Arino)

**Problems 6.**

- Lectures 13. & 14 Zoonotic spillover (Greer)

**Problems 7.**

- Lecture 15. Ch 8. Controlling Infectious Disease (Greer)

**Problems 8.**
