# Tentative schedule {-}

7 hours of work is scheduled August 20-30, with time to spend on projects increasing towards the end of the courses.

- Saturday August 19: arrive

- Sunday August 20: Both courses: lectures 1-2 + problems 1 (2 x 3hrs) + projects (1 hr)

- Monday August 21: Both courses: lectures 3-4 + problems 2 + projects (1 hr)

- Tues August 22: Both courses: lecture 5-6 + problems 3 + projects (1 hr)

- Wed August 23: Both courses: lecture 7-8 + problems 4 + guest lecture 1

- Thurs August 24: Both courses: lecture 9-10 + problems 5 + projects (1 hr)

- Fri August 25: Both courses: lecture 11 (2 x 1 hr) + guest lecture 2 (1 hr) + projects (4 hrs)

- Sat August 26: Both courses: lecture 12 (2 x 1 hr) + problems 6 (2 x 1 hr) + project (3 hr)

- Sun August 27: Both courses: lecture 13 + guest lecture 3 (1 hr) + project (5 hrs)

- Mon August 28: Both course: lecture 14 + problems 7 + project (3 hrs)

- Tues August 29: Course 1: lecture 15 (1 hour) + problems 8 (1 hour) + project (5 hours)

- Wed August 30: Course 2: lecture 15 + problems 8 + projects (5 hrs)
