# Problems - Mathematical Epidemiology {.unlisted .unnumbered #mathepiprobs}

- **Problems 1.1 Simple models and Host heterogeneity** (Chs 2 & 3 of Keeling and Rohani - Greer; TA - Li)
    + [Problems 1.1.Rmd](https://github.com/ahurford/ss-amy-greer/blob/main/August%2020_2023/Simple%20Models/Problemset1_1%20Simple%20Models.Rmd)^
    + [Image files](https://github.com/ahurford/ss-amy-greer/tree/main/August%2020_2023/Simple%20Models)
    + [.pdf](https://github.com/ahurford/ss-amy-greer/blob/main/August%2020_2023/Simple%20Models/Problems1_1-Simple-Models_Greer_Instructor.pdf)

^Requires that you have [installed Rmarkdown](https://bookdown.org/yihui/rmarkdown/installation.html)

\

- **Problems 1.2 Host heterogeneity and Multipathogen/Multihost** (Chs 3 & 4 of Keeling and Rohani - Heffernan; TA - Li)
    + [Problem Set 1.2](probset-multihost-multipath.pdf)
    
\

- **Problems 1.3 Within-host models** (Heffernan; TA - Su)
    + [julien-lectures/ASSIGNMENTS/exercises-metapopulations-introductions.texProblem Set 1.3](probset-inhost.pdf)

\

- **Problems 1.4 Pathogen evolution and temporally-forced models** (Ch 5 of Keeling and Rohani - Heffernan; TA - Baafi)
    + [Problem Set 1.4-evolution](probset-evolution.pdf)
    + [Problem Set 1.4-seasonality](probset-seasonality.pdf)

\

- **Problems 1.5 Stochastic dynamics and spatial models** (Ch 6 & 7 of Keeling and Rohani - Arino; TA - Li)
    + [Problem Set 1.5-stochastics](exercises-stochastic.pdf)

\

- **Problems 1.6 Spatial models and importations** (Ch 7 of Keeling and Rohani - Arino; TA - Li)
    + [Problem Set 1.6-metapops](exercises-metapopulations-importations.pdf)

\

- **Problems 1.7 Zoonotic spillover** (Greer; TA - Forero)
  + [Problems 1.7.Rmd](https://github.com/ahurford/ss-amy-greer/blob/main/August%2027_2023/Zoonotic%20spillover/Problemset%201_7%20Spillover.Rmd)
  + [Problems 1.7.pdf](https://github.com/ahurford/ss-amy-greer/blob/main/August%2027_2023/Zoonotic%20spillover/Zoonotic%20spillover%20Problems%201_7.pdf)

\

- **Problems 1.8 Controlling infectious diseases** (Ch 8 of Keeling and Rohani - Greer; TA - Su)
  + [Problems 1.8.Rmd](https://github.com/ahurford/ss-amy-greer/blob/main/August%2029_2023/Controlling%20Infectious%20Diseases/Problemset%201_8%20Interventions.Rmd)

