---
output:
  html_document: default
  word_document: default
---
# Final projects {-}

Final projects that were completed as part of the AARMS-EIDM summer school were:

1. **Conditions for forming and suspending the Atlantic bubble** by Tanuja Das, Ravindu Upasena, Qiuyi Su, Tangjuan Li, and Yurong Zhang. _Defines promising mathematical conditions for forming and suspending a travel bubble._

1. **An SEIR model with pandemic fatigue** by Rhiannon Loster, Benjamin Benteke, and Pengfei Yue. [Github repository](https://github.com/maxwellyue1/AARMS_Summer_School) and [Shiny app](https://rloster.shinyapps.io/AARMS2023/).

1. **Topical Acaricides on Rodents as a One Health Intervention Against Lyme Disease: A Epidemiological Modelling Study** by Bruce Chidley, Lauren Farrell, Geneva Liwag, Thaneswary Rajanderan, and Sophie Stelmach.

1. **Investigating the conditions for locally transmitted dengue infections** by Leyi Jiang, Grace Nichol, and Michele Bergevin.

1. **Exploring Cross-Species Transmission through ODE Models Informed by Phylogenetic Analysis** by Sana Naderi and Norma Forero. [Github repository](https://github.com/Saannah/AARMS) and [QuidiPhyDy R package](https://github.com/Saannah/QuidiPhydy) (on CRAN).

1. **Modelling Human Induced Allee Effects on Biological Invasion in a Two Patch Model** by Manuel Perez, Elise Woodward, and Zahresh Walji. [Github repository](https://github.com/ewoodwar/Final-project-2023-AARMS).

1. **An SIARV model: dynamics and data fitting** by Jessa Marley, Shab Molan, Francisca Olajide, and Greg Forkutza.

1. **A Time-Delayed and Drug-Controlled Within-Host Model** by Rushi Chaudhary, Shiheng Fan, Tian Hou, Zhimin Li, and Yuanxi Yue. _Strong mathematical analysis._

1. **Investigating the spread and establishment of Chikungunya in Florida through stochastic and deterministic modelling** and **Weather and _Chikungunya_ transmission dynamics** by Antonio Gondim, Leonardo Shultz, and Rebeca Falcao. _Two promising projects with strong integration of data and models._

1. **A two patch model of dengue fever dynamics** by George Adu-Boahen, Francis Anokye, Joseph Baafi, and Giuseppe Pasquilino.