# Participant demographic summary {-}

## Affiliation {- .unlisted}
British Columbia CDC (1)

University of Guelph (6)

McGill University (1)

McMaster University (2)

University of Miami (2)

Memorial University (11)

Queen's University (1)

Simon Fraser University (2)

University of Montreal (2)

University of Ottawa (1)

University of British Columbia Okanagan (1)

University of New Brunswick (2)

University of Toronto (1)

University of Western Ontario (1)

York University (5)

Total participants: 39

AARMS affiliation (11), Past affiliation with the African Institute of Mathematical Sciences (3), CANMOD (2), OMNI-REUNIS (6), Mathematics for Public Health (5).

## Career stage {- .unlisted}
Undergraduate or beginning graduate student (6)

MSc student (7)

PhD student (18)

Postdoctoral fellow (4)

Early career researcher (1)

Other (4)

## Degree program/primary area {- .unlisted}
Mathematics and statistics (32)

Epidemiology, public health or biology (10)

Other (1).

## Gender, Indigenous Peoples, visible minitories, persons with disabilities {- .unlisted}
Male (15)

Female (24)

Indigenous (< 5 participants)

Visible minorities (16)

Caucasian (14)

Disabilities (0)
