# Preparation for students with limited coding experience {.unlisted .unnumbered #prepcoding}

Coding involves some knowledge of specific languages (for the summer school this is R), however the most important coding skill is having a good idea for how to do what you want to do (i.e., writing pseudo-code), having experience solving similar problems (the summer school aims to give you this experience for your own future research), and being skilled at debugging.

If you don't feel confident with your coding, I recommend being open to learning from a fellow summer school participant that is strong at coding - this is how many of us learned.

If you want to learn more R functions, you can complete the [software carpentary](http://swcarpentry.github.io/r-novice-inflammation/aio.html) modules, or consult my [R guide](https://ahurford.github.io/quant-guide-all-courses/) (there are other similar guides that might be better), but I'm not sure this is necessary.

Debugging comes with experience, and it can help to view it as hypothesis testing. Chapters 3 and 4 of Dietze 2017 are not covered in the summer school, but this is some good content related to handling data and scientific computing.

The summer school involves a guest lecture from Steve Walker. If you are interested in best practices and learning coding, take the opportunity to ask Steve's advice.
