# Problems 2.8. {.unlisted .unnumbered #probs-2-8}

1. In a group of 3 to 4, work together to make a consequence table related to the implementation of capacity limits and/or social distancing in retail, schools, and community recreation venues during a pandemic due to an airborne respiratory illness. Have each group member play the role of a different stakeholder. Do not do the modelling to determine the values in the consequence table, instead represent these as values, $v_{i,j}$.
    + Write a paragraph describing how you applied some of the principles described in Chapter 17 of Dietze.
    + Provide any inequalities related to the values, $v_{i,j}$, you expect in the consequence table. Describe the trade-offs the consequence table reveals.
    + Provide a simple epidemiological model that might form the deterministic skeleton for a model that could be used to estimate the values in the consequence table.

2. Write 1 paragraph, which is an example of something that in hindsight was a “failure in imagination” during the COVID-19 pandemic.

3. Describe how a mathematical model (preferably with equations) could be extended to consider the "failure in imagination" that you described in 2.

4. Visit [https://www.ipcc.ch/report/ar6/wg2/](https://www.ipcc.ch/report/ar6/wg2/). Find a figure of future carbon emission scenarios (Reconstruction Concentration Pathways (RCPs)), and their impacts. Write a paragraph that describes how the presentation of projections in the IPCC report are consistent with the principles discussed in Chapter 17 of Dietze (2017) for scenario construction.

