# Antimicrobial-resistant Gonorrhea {.unlisted .unnumbered #ag2}

We are facing the very real possibility that gonorrhoea infections are going to become untreatable in the not so distant [future](https://www.ctvnews.ca/health/highly-resistant-gonorrhea-on-the-rise-in-canada-other-countries-world-health-organization-1.6492406). Antimicrobial resistance (AMR) is making gonorrhoea infections more and more difficult to treat. Previous research has shown that an important consideration for modelling gonorrhoea is the role of a “core group” (a group of individuals who have much higher contact rates than the rest of the population) (see: [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4760416/)). At the same time, some new research suggests that doxycycline PEP (post-exposure prophylaxis with doxycycline (within 3 days) after unprotected sex in men who have sex with men (MSM) and transgender women is very effective. However, it seems like increased use of doxy-PEP could further contribute to increasing antimicrobial resistance. Develop a model to answer the following question: Under what conditions do you think that introducing doxy-PREP into the public health toolbox for this population will or will not contribute to AMR?
