#!/bin/bash

# Render the lectures and copy them where they need 
# to be (/docs in the repo)
# Do a local render (might not be most recent version
# of marp)
# Does pull and push, so beware..

rm *.html
npx marp  --html 2023-*.md
cp *.html ../../docs/
git pull
git commit -a -m "Update the slides"
git push
